### PR TITLE
russian i18n for bar.powerlines

### PR DESCRIPTION
**Pull request by antsif-a**
https://github.com/Anuken/Mindustry/pull/2906

### CODE REVIEW

**Comment by Voz-Duh** [comment]
Why not: `Подключений: {0}/{1}`?

**Comment by antsif-a** [comment]
@Voz-Duh, comparing with other translations in the block statistics, there is a translation in the nominative case. For example: `Предметы: {0}`.

**Comment by Voz-Duh** [comment]
Okay

**Comment by antsif-a** [comment]
I'll translate it once original PR merged.

**Pull request closed without merging**
